[build-system]        
requires = [
  "setuptools>=42",
  "torch>1.10,<1.12",
  "scikit-build",
  "numpy==1.22.4",
  ## out-comment not install cmake/ninja via pip
  "cmake>=3.21",
  "ninja; platform_system!='Windows'",
  "pkg-config",
]
build-backend = "setuptools.build_meta"
